service: http-service
app: warhammer-aos

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-domain-manager

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  customDomain:
    domainName: aos-api.com
    certificateName: aos-api.com
    stage: ${self:provider.stage}
    createRoute53Record: false
    enabled: true
    endpointType: 'edge'
    securityPolicy: tls_1_2

functions:
  armies:
    handler: ./bin/armies
    events:
      - http:
          path: armies
          method: GET

