version: '3'

includes:
  win: ./Taskfile_windows.yml

tasks:
  validate:
    desc: Validate JSON files against schema
    summary: |
      Validate your JSON files against the schema

      This ensures that we've got consistency between data sources across
      the repository.
    cmds:
      - ajv test -s schema.json -d "./data/json/*.json" --strict=false --valid | grep '$!"passed test"'

  build:
    desc: Build Go binary for multiple distributions
    cmds:
      - go build -o bin/armies lambda/armies/main.go

  lint:
    desc: Lint code for quality controls
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run the test suite
    cmds:
      - go test -v ./...

  clean:
    desc: Clean up resources
    cmds:
      - rm -rf ./bin ./vendor go.sum

  deploy:
    desc: Deploy serverless functions
    cmds:
      - sls deploy

  docs:
    desc: Generate markdown documenation
    cmds:
      - gomarkdoc ./internal/handlers

  invoke:
    desc: Invoke lambda function locally
    cmds:
      - serverless invoke local --function armies -d '{}'
