version: '3'

includes:
  win: ./Taskfile_windows.yml

tasks:
  default:
    desc: Default tasks
    cmds:
      - task: setup
      - task: lint
      - task: build

  build:
    desc: Build binaries and package up application
    cmds:
      - task: build:go
      - task: build:pkg

  build:go:
    desc: Build Go binary for multiple distributions
    cmds:
      - env GOOS=linux go build -o bin/armies lambda/armies/main.go
      - env GOOS=linux go build -o bin/indexes lambda/indexes/main.go
      - env GOOS=linux go build -o bin/robots lambda/robots/main.go
    sources:
      - ./**/*.go
    generates:
      - bin/armies
      - bin/indexes

  build:pkg:
    desc: Package up application
    cmds:
      - sls package

  test:
    desc: Run all tests
    cmds:
      - task: test:lint
      - task: test:go
      - task: test:json

  test:lint:
    desc: Test code for stylistic errors
    cmds:
      - golangci-lint run ./...

  test:go:
    desc: Test methods with suite
    cmds:
      - go test -v ./...

  test:json:
    desc: Test JSON files against schema
    cmds:
      - ajv validate -s schema.json -d "./data/armies/*.json" --strict=false

  invoke:
    desc: Invoke lambda function locally
    cmds:
      - sls invoke local --function indexes -d "{}"
      - sls invoke local --function robots -d "{}"
      - sls invoke local --function armies -d "{}"
      - sls invoke local --function armies-name --path ./armies.test.json

  deploy:
    desc: Deploy serverless functions
    cmds:
      - sls deploy -c dev.serverless.yml

  deploy:prod:
    desc: Deploy production version of serverless functions
    cmds:
      - sls deploy

