version: '3'

includes:
  win: ./Taskfile_windows.yml

tasks:

  validate:
    desc: Validate JSON files against schema
    summary: |
      Validate your JSON files against the schema

      This ensures that we've got consistency between data sources across
      the repository.
    cmds:
      - ajv validate -s schema.json -d "./data/armies/*.json" --strict=false

  build:
    desc: Build Go binary for multiple distributions
    cmds:
      - go build -o bin/armies lambda/armies/main.go
      - go build -o bin/indexes lambda/indexes/main.go

  lint:
    desc: Lint code for quality controls
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run the test suite
    cmds:
      - go test -v ./...

  clean:
    desc: Clean up resources
    cmds:
      - rm -rf ./bin ./vendor go.sum

  deploy:
    desc: Deploy serverless functions
    cmds:
      - sls deploy -c dev.serverless.yml

  deploy:prod:
    desc: Deploy production version of serverless functions
    cmds:
      - sls deploy

  gomodgen:
    desc: Generate go.mod
    cmds:
      - chmod u+x ./scripts/gomod.sh
      - ./scripts/gomod.sh

  invoke:
    desc: Invoke lambda function locally
    cmds:
      - sls invoke local --function indexes -d "{}"
      - sls invoke local --function armies -d "{}"
      - sls invoke local --function armies --path ./armies.test.json
